export const paths = {
  course: '/course/:id',
  courses: '/courses',
  error: '/error/:code',
  landing: '/',
  login: '/login',
  privacy: '/privacy',
  recent: '/recent',
  register: '/register',
  resetPassword: '/reset-password',
  review: {
    create: '/review',
    update: '/review/:id',
  },
  reviews: '/reviews',
  setPassword: '/set-password',
  terms: '/terms',
  userProfile: '/user/profile',
  userReviews: '/user/reviews',
};
